<?xml version="1.0" encoding="utf-8"?><Database Name="Webshop" Class="WebshopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NUSSI-PC\SQLEXPRESS;Initial Catalog=Webshop;Integrated Security=True" SettingsObjectName="Webshop.Common.Properties.Settings" SettingsPropertyName="WebshopConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bestellposition" Member="Bestellposition">
    <Type Name="Bestellposition">
      <Column Name="Produkt_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Bestellung_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Menge" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bestellung_Bestellposition" Member="Bestellung" ThisKey="Bestellung_ID" OtherKey="Bestellung_ID" Type="Bestellung" IsForeignKey="true" />
      <Association Name="Produkt_Bestellposition" Member="Produkt" ThisKey="Produkt_ID" OtherKey="Produkt_ID" Type="Produkt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bestellung" Member="Bestellung">
    <Type Name="Bestellung">
      <Column Name="Bestellung_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bestelldatum" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Versandkosten" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Rechnungsbetrag" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Bestellung_Bestellposition" Member="Bestellposition" ThisKey="Bestellung_ID" OtherKey="Bestellung_ID" Type="Bestellposition" />
      <Association Name="User_Bestellung" Member="User" ThisKey="User_ID" OtherKey="User_ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Produkt" Member="Produkt">
    <Type Name="Produkt">
      <Column Name="Produkt_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Kurzbezeichnung" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Langbezeichnung" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Steuersatz" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Preis_netto" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Zutaten" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Produkt_Bestellposition" Member="Bestellposition" ThisKey="Produkt_ID" OtherKey="Produkt_ID" Type="Bestellposition" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="User_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Vorname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Nachname" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Adresse" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="PLZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ort" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Land" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Telefonnummer" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="Benutzername" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Passwort" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="Usergruppe_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Bestellung" Member="Bestellung" ThisKey="User_ID" OtherKey="User_ID" Type="Bestellung" />
      <Association Name="Usergruppe_User" Member="Usergruppe" ThisKey="Usergruppe_ID" OtherKey="Usergruppe_ID" Type="Usergruppe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usergruppe" Member="Usergruppe">
    <Type Name="Usergruppe">
      <Column Name="Usergruppe_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Usergruppenbezeichnung" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Association Name="Usergruppe_User" Member="User" ThisKey="Usergruppe_ID" OtherKey="Usergruppe_ID" Type="User" />
    </Type>
  </Table>
</Database>